# Generated by Django 3.2.19 on 2023-05-18 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 15, 14, 23, 298471)),
        ),
    ]
