# Generated by Django 3.2.19 on 2023-05-18 11:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cab', '0003_rename_user_cab_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=datetime.datetime(2023, 5, 18, 14, 30, 57, 819922))),
                ('text', models.CharField(max_length=1024)),
                ('state', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=1024)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cab.cab')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
