# Generated by Django 3.2.19 on 2023-05-18 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 15, 14, 23, 299457)),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
