# Generated by Django 3.2.19 on 2023-05-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0002_cab_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cab',
            old_name='user',
            new_name='user_id',
        ),
    ]
